[package]
name = "prism_render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prism_core = { path = "../prism_core" }
prism_hvs = { path = "../prism_hvs" }
prism_sync = { path = "../prism_sync" }
image.workspace = true
thiserror.workspace = true

[dev-dependencies]
