//! # Constrained Halo Glyph Bitmaps
//!
//! 5×7 monospace character bitmaps using the **Constrained Halo** pattern:
//! - `Some(0)` = dark stroke (State 0, fixed)
//! - `Some(2)` = light halo (State 2, fixed) — ONLY the immediate 1-pixel border
//! - `None` = free/transparent cell (solver chooses for RS parity; renderer shows through)
//!
//! True Transparency: everything outside the 1-pixel halo is `None`, allowing
//! the underlying halftone art to show through the glyph bounding box.

/// Width of each glyph in modules.
pub const GLYPH_WIDTH: usize = 5;

/// Height of each glyph in modules.
pub const GLYPH_HEIGHT: usize = 7;

/// A 5×7 Constrained Halo glyph. `glyph[row][col]`, row 0 is top.
pub type HaloGlyph = [[Option<u8>; GLYPH_WIDTH]; GLYPH_HEIGHT];

/// Blank glyph (all free) used as fallback for unknown characters.
const BLANK: HaloGlyph = [[None; GLYPH_WIDTH]; GLYPH_HEIGHT];

/// Shorthand aliases for readability in glyph definitions.
const D: Option<u8> = Some(0); // Dark stroke
const L: Option<u8> = Some(2); // Light halo (1px border only)
const F: Option<u8> = None;    // Free / transparent

/// Get the Constrained Halo glyph for a character. Returns blank for unknowns.
/// Lowercase is mapped to uppercase.
///
/// Each glyph uses true transparency: only the stroke and its immediate
/// 8-connected 1-pixel halo are constrained. All other cells are `None`.
pub fn get_glyph(ch: char) -> HaloGlyph {
    match ch.to_ascii_uppercase() {
        'A' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [D, L, L, L, D],
            [D, D, D, D, D],
            [D, L, L, L, D],
            [D, L, F, L, D],
            [L, L, F, L, L],
        ],
        'B' => [
            [D, D, D, L, L],
            [D, L, L, D, L],
            [D, D, D, L, L],
            [D, L, L, D, L],
            [D, D, D, L, L],
            [L, L, L, L, F],
            [F, F, F, F, F],
        ],
        'C' => [
            [L, L, D, D, L],
            [L, D, L, L, D],
            [D, L, L, L, L],
            [D, L, F, F, F],
            [D, L, L, L, L],
            [L, D, L, L, D],
            [L, L, D, D, L],
        ],
        'D' => [
            [D, D, D, L, L],
            [D, L, L, D, L],
            [D, L, L, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [D, L, L, D, L],
            [D, D, D, L, L],
        ],
        'E' => [
            [D, D, D, D, D],
            [D, L, L, L, L],
            [D, L, L, L, F],
            [D, D, D, L, F],
            [D, L, L, L, F],
            [D, L, L, L, L],
            [D, D, D, D, D],
        ],
        'F' => [
            [D, D, D, D, D],
            [D, L, L, L, L],
            [D, L, L, L, F],
            [D, D, D, L, F],
            [D, L, L, L, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
        ],
        'G' => [
            [L, L, D, D, L],
            [L, D, L, L, D],
            [D, L, L, L, L],
            [D, L, D, D, D],
            [D, L, L, L, D],
            [L, D, L, L, D],
            [L, L, D, D, L],
        ],
        'H' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [D, D, D, D, D],
            [D, L, L, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
        ],
        'I' => [
            [D, D, D, D, D],
            [L, L, D, L, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [L, L, D, L, L],
            [D, D, D, D, D],
        ],
        'J' => [
            [F, F, F, L, D],
            [F, F, F, L, D],
            [F, F, F, L, D],
            [L, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        'K' => [
            [D, L, L, L, D],
            [D, L, L, D, L],
            [D, L, D, L, L],
            [D, D, L, L, F],
            [D, L, D, L, L],
            [D, L, L, D, L],
            [D, L, L, L, D],
        ],
        'L' => [
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, L, L, L],
            [D, D, D, D, D],
        ],
        'M' => [
            [D, L, L, L, D],
            [D, D, L, D, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, L, L, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
        ],
        'N' => [
            [D, L, L, L, D],
            [D, D, L, L, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, L, L, D, D],
            [D, L, L, L, D],
            [D, L, F, L, D],
        ],
        'O' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [D, L, L, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        'P' => [
            [D, D, D, L, L],
            [D, L, L, D, L],
            [D, L, L, D, L],
            [D, D, D, L, L],
            [D, L, L, L, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
        ],
        'Q' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [D, L, L, L, D],
            [D, L, L, L, D],
            [D, L, D, L, D],
            [L, D, L, D, L],
            [L, L, D, L, D],
        ],
        'R' => [
            [D, D, D, L, L],
            [D, L, L, D, L],
            [D, L, L, D, L],
            [D, D, D, L, L],
            [D, L, D, L, L],
            [D, L, L, D, L],
            [D, L, L, L, D],
        ],
        'S' => [
            [L, L, D, D, L],
            [L, D, L, L, D],
            [L, D, L, L, L],
            [L, L, D, L, L],
            [F, L, L, D, L],
            [L, L, L, L, D],
            [L, D, D, L, L],
        ],
        'T' => [
            [D, D, D, D, D],
            [L, L, D, L, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        'U' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        'V' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        'W' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, D, L, D, D],
            [D, L, L, L, D],
        ],
        'X' => [
            [D, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
            [L, D, L, D, L],
            [D, L, L, L, D],
            [D, L, F, L, D],
        ],
        'Y' => [
            [D, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        'Z' => [
            [D, D, D, D, D],
            [L, L, L, L, D],
            [F, L, L, D, L],
            [L, L, D, L, L],
            [L, D, L, L, F],
            [D, L, L, L, L],
            [D, D, D, D, D],
        ],
        '0' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [D, L, L, L, D],
            [D, L, F, L, D],
            [D, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        '1' => [
            [F, L, D, L, F],
            [L, D, D, L, F],
            [L, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [L, D, D, D, L],
        ],
        '2' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [L, L, L, L, D],
            [F, L, L, D, L],
            [L, L, D, L, L],
            [L, D, L, L, L],
            [D, D, D, D, D],
        ],
        '3' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [L, L, L, L, D],
            [L, L, D, L, L],
            [L, L, L, L, D],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        '4' => [
            [F, F, L, D, L],
            [F, L, D, D, L],
            [L, D, L, D, L],
            [D, D, D, D, D],
            [L, L, L, D, L],
            [F, F, L, D, L],
            [F, F, L, D, L],
        ],
        '5' => [
            [D, D, D, D, D],
            [D, L, L, L, L],
            [D, D, D, L, L],
            [L, L, L, D, L],
            [L, L, L, L, D],
            [L, L, L, D, L],
            [L, D, D, L, L],
        ],
        '6' => [
            [L, L, D, D, L],
            [L, D, L, L, L],
            [D, L, L, L, F],
            [D, D, D, L, L],
            [D, L, L, D, L],
            [D, L, L, D, L],
            [L, D, D, L, L],
        ],
        '7' => [
            [D, D, D, D, D],
            [L, L, L, L, D],
            [F, F, L, D, L],
            [F, L, L, D, L],
            [F, L, D, L, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        '8' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [L, L, D, L, L],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [L, L, D, L, L],
        ],
        '9' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [L, L, D, D, L],
            [F, L, L, L, D],
            [L, L, L, D, L],
            [L, D, D, L, L],
        ],
        ' ' => BLANK,
        '.' => [
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, L, L, L, F],
            [F, L, D, L, F],
            [F, L, L, L, F],
        ],
        '!' => [
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, L, L, F],
            [F, L, D, L, F],
        ],
        '?' => [
            [L, L, D, L, L],
            [L, D, L, D, L],
            [L, L, L, L, D],
            [F, L, L, D, L],
            [F, L, D, L, L],
            [F, L, L, L, F],
            [F, L, D, L, F],
        ],
        '-' => [
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [D, D, D, D, D],
            [L, L, L, L, L],
            [F, F, F, F, F],
            [F, F, F, F, F],
        ],
        ':' => [
            [F, L, L, L, F],
            [F, L, D, L, F],
            [F, L, L, L, F],
            [F, F, F, F, F],
            [F, L, L, L, F],
            [F, L, D, L, F],
            [F, L, L, L, F],
        ],
        '#' => [
            [L, D, L, D, L],
            [L, D, L, D, L],
            [D, D, D, D, D],
            [L, D, L, D, L],
            [D, D, D, D, D],
            [L, D, L, D, L],
            [L, D, L, D, L],
        ],
        '/' => [
            [F, F, F, L, D],
            [F, F, L, D, L],
            [F, F, L, D, L],
            [F, L, D, L, F],
            [L, D, L, F, F],
            [L, D, L, F, F],
            [D, L, F, F, F],
        ],
        _ => BLANK,
    }
}

/// Count the number of free cells (None) in a glyph.
pub fn free_cell_count(glyph: &HaloGlyph) -> usize {
    glyph.iter().flat_map(|row| row.iter()).filter(|c| c.is_none()).count()
}
