//! # Constrained Halo Glyph Bitmaps
//!
//! 5×7 monospace character bitmaps using the **Constrained Halo** pattern:
//! - `Some(0)` = dark stroke (State 0, fixed)
//! - `Some(2)` = light halo / quiet zone (State 2, fixed)
//! - `None` = free cell (Z3 chooses the value for RS parity)
//!
//! The halo ensures visual contrast around strokes. Free cells (~30% of each
//! glyph box) provide mathematical breathing room for the Z3 parity solver.

/// Width of each glyph in modules.
pub const GLYPH_WIDTH: usize = 5;

/// Height of each glyph in modules.
pub const GLYPH_HEIGHT: usize = 7;

/// A 5×7 Constrained Halo glyph. `glyph[row][col]`, row 0 is top.
pub type HaloGlyph = [[Option<u8>; GLYPH_WIDTH]; GLYPH_HEIGHT];

/// Blank glyph (all free) used as fallback for unknown characters.
const BLANK: HaloGlyph = [[None; GLYPH_WIDTH]; GLYPH_HEIGHT];

/// Shorthand aliases for readability in glyph definitions.
const D: Option<u8> = Some(0); // Dark stroke
const L: Option<u8> = Some(2); // Light halo
const F: Option<u8> = None;    // Free (Z3 decides)

/// Get the Constrained Halo glyph for a character. Returns blank for unknowns.
/// Lowercase is mapped to uppercase.
pub fn get_glyph(ch: char) -> HaloGlyph {
    match ch.to_ascii_uppercase() {
        'A' => [
            [F, L, D, L, F],
            [L, D, F, D, L],
            [D, L, F, L, D],
            [D, D, D, D, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [F, F, F, F, F],
        ],
        'B' => [
            [D, D, D, L, F],
            [D, L, L, D, L],
            [D, D, D, L, F],
            [D, L, L, D, L],
            [D, D, D, L, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
        ],
        'C' => [
            [F, L, D, D, L],
            [L, D, L, L, D],
            [D, L, F, F, L],
            [D, L, F, F, F],
            [D, L, F, F, L],
            [L, D, L, L, D],
            [F, L, D, D, L],
        ],
        'D' => [
            [D, D, D, L, F],
            [D, L, L, D, L],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, L, D, L],
            [D, D, D, L, F],
        ],
        'E' => [
            [D, D, D, D, D],
            [D, L, L, L, L],
            [D, L, F, F, F],
            [D, D, D, L, F],
            [D, L, F, F, F],
            [D, L, L, L, L],
            [D, D, D, D, D],
        ],
        'F' => [
            [D, D, D, D, D],
            [D, L, L, L, L],
            [D, L, F, F, F],
            [D, D, D, L, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
        ],
        'G' => [
            [F, L, D, D, L],
            [L, D, L, L, D],
            [D, L, F, F, L],
            [D, L, D, D, D],
            [D, L, F, L, D],
            [L, D, L, L, D],
            [F, L, D, D, L],
        ],
        'H' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, D, D, D, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
        ],
        'I' => [
            [D, D, D, D, D],
            [L, L, D, L, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [L, L, D, L, L],
            [D, D, D, D, D],
        ],
        'J' => [
            [L, L, L, L, D],
            [F, F, F, L, D],
            [F, F, F, L, D],
            [F, F, F, L, D],
            [D, L, F, L, D],
            [D, L, L, D, L],
            [L, D, D, L, F],
        ],
        'K' => [
            [D, L, F, L, D],
            [D, L, L, D, L],
            [D, L, D, L, F],
            [D, D, L, F, F],
            [D, L, D, L, F],
            [D, L, L, D, L],
            [D, L, F, L, D],
        ],
        'L' => [
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, L, L, L],
            [D, D, D, D, D],
        ],
        'M' => [
            [D, L, F, L, D],
            [D, D, L, D, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
        ],
        'N' => [
            [D, L, F, L, D],
            [D, D, L, L, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, L, L, D, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
        ],
        'O' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [L, D, L, D, L],
            [F, L, D, L, F],
        ],
        'P' => [
            [D, D, D, L, F],
            [D, L, L, D, L],
            [D, L, L, D, L],
            [D, D, D, L, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
            [D, L, F, F, F],
        ],
        'Q' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, D, L, D],
            [L, D, L, D, L],
            [F, L, D, L, D],
        ],
        'R' => [
            [D, D, D, L, F],
            [D, L, L, D, L],
            [D, L, L, D, L],
            [D, D, D, L, F],
            [D, L, D, L, F],
            [D, L, L, D, L],
            [D, L, F, L, D],
        ],
        'S' => [
            [F, L, D, D, L],
            [L, D, L, L, D],
            [L, D, L, F, F],
            [F, L, D, L, F],
            [F, F, L, D, L],
            [L, L, L, D, L],
            [L, D, D, L, F],
        ],
        'T' => [
            [D, D, D, D, D],
            [L, L, D, L, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        'U' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [L, D, L, D, L],
            [F, L, D, L, F],
        ],
        'V' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [F, L, D, L, F],
        ],
        'W' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, F, L, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, D, L, D, D],
            [D, L, F, L, D],
        ],
        'X' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [L, D, L, D, L],
            [F, L, D, L, F],
            [L, D, L, D, L],
            [D, L, F, L, D],
            [D, L, F, L, D],
        ],
        'Y' => [
            [D, L, F, L, D],
            [D, L, F, L, D],
            [L, D, L, D, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        'Z' => [
            [D, D, D, D, D],
            [L, L, L, L, D],
            [F, F, L, D, L],
            [F, L, D, L, F],
            [L, D, L, F, F],
            [D, L, L, L, L],
            [D, D, D, D, D],
        ],
        '0' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [D, L, D, L, D],
            [L, D, L, D, L],
            [F, L, D, L, F],
        ],
        '1' => [
            [F, L, D, L, F],
            [L, D, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [L, D, D, D, L],
        ],
        '2' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [F, L, F, D, L],
            [F, F, L, D, L],
            [F, L, D, L, F],
            [L, D, L, F, F],
            [D, D, D, D, D],
        ],
        '3' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [F, F, F, D, L],
            [F, F, D, L, F],
            [F, F, F, D, L],
            [L, D, L, D, L],
            [F, L, D, L, F],
        ],
        '4' => [
            [F, F, L, D, L],
            [F, L, D, D, L],
            [L, D, L, D, L],
            [D, D, D, D, D],
            [F, F, L, D, L],
            [F, F, L, D, L],
            [F, F, L, D, L],
        ],
        '5' => [
            [D, D, D, D, D],
            [D, L, L, L, L],
            [D, D, D, L, F],
            [L, L, L, D, L],
            [F, F, F, D, L],
            [L, L, L, D, L],
            [L, D, D, L, F],
        ],
        '6' => [
            [F, L, D, D, L],
            [L, D, L, L, F],
            [D, L, F, F, F],
            [D, D, D, L, F],
            [D, L, L, D, L],
            [D, L, L, D, L],
            [L, D, D, L, F],
        ],
        '7' => [
            [D, D, D, D, D],
            [L, L, L, L, D],
            [F, F, F, D, L],
            [F, F, L, D, L],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        '8' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [F, L, D, L, F],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [F, L, D, L, F],
        ],
        '9' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [L, D, L, D, L],
            [F, L, D, D, D],
            [F, F, F, L, D],
            [F, L, L, D, L],
            [L, D, D, L, F],
        ],
        ' ' => BLANK,
        '.' => [
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
        ],
        '!' => [
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, F, L, F, F],
            [F, L, D, L, F],
        ],
        '?' => [
            [F, L, D, L, F],
            [L, D, L, D, L],
            [F, F, F, D, L],
            [F, F, L, D, L],
            [F, L, D, L, F],
            [F, F, L, F, F],
            [F, L, D, L, F],
        ],
        '-' => [
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [D, D, D, D, D],
            [F, F, F, F, F],
            [F, F, F, F, F],
            [F, F, F, F, F],
        ],
        ':' => [
            [F, F, F, F, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, F, F, F, F],
            [F, L, D, L, F],
            [F, L, D, L, F],
            [F, F, F, F, F],
        ],
        '#' => [
            [F, D, L, D, F],
            [F, D, L, D, F],
            [D, D, D, D, D],
            [F, D, L, D, F],
            [D, D, D, D, D],
            [F, D, L, D, F],
            [F, D, L, D, F],
        ],
        _ => BLANK,
    }
}

/// Count the number of free cells (None) in a glyph.
pub fn free_cell_count(glyph: &HaloGlyph) -> usize {
    glyph.iter().flat_map(|row| row.iter()).filter(|c| c.is_none()).count()
}
